import {
    StudentIcon,
    UserIcon,
    BookIcon,
    CurrencyDollarIcon,
    BellIcon,
    CalendarIcon,
    WarningIcon,
    CheckCircleIcon,
} from "@phosphor-icons/react";

export const notifications = [
    {
        id: 1,
        title: "New Student Enrolled",
        description: "Alex Walker has been enrolled in SSC-II.",
        seen: true,
        Icon: StudentIcon,
        createdAt: "2026-06-15T08:30:00Z",
    },
    {
        id: 2,
        title: "Fee Payment Received",
        description: "Rs. 15,000 fee received from Sara Hughes for HSSC-I.",
        seen: true,
        Icon: CurrencyDollarIcon,
        createdAt: "2026-06-14T14:20:00Z",
    },
    {
        id: 3,
        title: "Schedule Updated",
        description: "Mathematics schedule for SSC-II has been updated.",
        seen: false,
        Icon: CalendarIcon,
        createdAt: "2026-06-14T10:00:00Z",
    },
    {
        id: 4,
        title: "New Teacher Assigned",
        description: "David Lee has been assigned to Computer Science class.",
        seen: false,
        Icon: UserIcon,
        createdAt: "2026-06-13T09:15:00Z",
    },
    {
        id: 5,
        title: "Low Attendance Alert",
        description: "Noah Khan's attendance has dropped below 70% in SSC-II.",
        seen: false,
        Icon: WarningIcon,
        createdAt: "2026-06-13T08:00:00Z",
    },
    {
        id: 6,
        title: "Fee Pending Reminder",
        description: "3 students in HSSC-II have pending fee payments.",
        seen: true,
        Icon: CurrencyDollarIcon,
        createdAt: "2026-06-12T16:45:00Z",
    },
    {
        id: 7,
        title: "Exam Results Published",
        description: "Mid-term results for HSSC-I have been published.",
        seen: true,
        Icon: CheckCircleIcon,
        createdAt: "2026-06-11T12:00:00Z",
    },
    {
        id: 8,
        title: "New Subject Added",
        description: "Biology has been added to SSC-I curriculum.",
        seen: false,
        Icon: BookIcon,
        createdAt: "2026-06-10T11:30:00Z",
    },
    {
        id: 9,
        title: "Staff Meeting Scheduled",
        description: "Faculty meeting scheduled for June 20th at 3:00 PM.",
        seen: false,
        Icon: BellIcon,
        createdAt: "2026-06-10T09:00:00Z",
    },
    {
        id: 10,
        title: "Student Transfer Request",
        description: "Bilal Sheikh has requested transfer from SSC-I to SSC-II.",
        seen: true,
        Icon: StudentIcon,
        createdAt: "2026-06-09T15:20:00Z",
    },
    {
        id: 11,
        title: "Expense Recorded",
        description: "Lab equipment expense of Rs. 45,000 recorded for HSSC-II.",
        seen: true,
        Icon: CurrencyDollarIcon,
        createdAt: "2026-06-08T13:10:00Z",
    },
    {
        id: 12,
        title: "Class Performance Alert",
        description: "Average score in Physics for HSSC-I is below 60%.",
        seen: false,
        Icon: WarningIcon,
        createdAt: "2026-06-08T10:00:00Z",
    },
    {
        id: 13,
        title: "New Member Joined",
        description: "Emma Garcia joined as Admin in your institute.",
        seen: true,
        Icon: UserIcon,
        createdAt: "2026-06-07T14:30:00Z",
    },
    {
        id: 14,
        title: "Attendance Report Ready",
        description: "Monthly attendance report for May 2026 is ready.",
        seen: false,
        Icon: CalendarIcon,
        createdAt: "2026-06-06T09:00:00Z",
    },
    {
        id: 15,
        title: "Fee Collection Summary",
        description: "Total Rs. 2,45,000 collected across all classes this week.",
        seen: true,
        Icon: CurrencyDollarIcon,
        createdAt: "2026-06-05T17:00:00Z",
    },
];
